apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-setup-app
  namespace: argocd
spec:
  project: default
  source:
#mention your own repo which include the helmfile.yaml and define the path
    repoURL: https://github.com/stwgtg/helmfile.git
    targetRevision: HEAD
    path: logging-setup
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2