apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: cmp-helmfile
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
          image: ghcr.io/helmfile/helmfile:latest
          imagePullPolicy: IfNotPresent
# Entrypoint should be Argo CD lightweight CMP server i.e. argocd-cmp-server
          command: [/var/run/argocd/argocd-cmp-server]
          volumeMounts:
            - mountPath: /var/run/argocd
              name: var-files
            - mountPath: /home/argocd/cmp-server/plugins
              name: plugins
            - mountPath: /home/argocd/cmp-server/config/plugin.yaml
              subPath: plugin.yaml
              name: cmp-helmfile
            - mountPath: /tmp
              name: cmp-tmp
          env:
            - name: HELM_CONFIG_HOME
              value: /tmp/helm/config
            - name: HELM_CACHE_HOME
              value: /tmp/helm/cache
            - name: HELM_DATA_HOME
              value: /tmp/helm/data
      volumes:
        - name: cmp-helmfile
          configMap:  
            name: cmp-helmfile
        - emptyDir: {}
          name: cmp-tmp


          